### ISSUE TITLE
git-annex snapshot fails to download -- "forbidden"

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-extensions#101]
this night got flooded with emails about failed jobs... (didn't happen before)  all are red now on https://github.com/datalad/datalad-extensions due to e.g.

[test (datalad-git-annex-latest)](https://github.com/datalad/datalad-extensions/runs/6892546678?check_suite_focus=true#step:3:255)
Process completed with exit code 1.

we released datalad-installer yesterday -- could that relate?

looks like

```
2022-06-15T04:17:05+0000 [INFO    ] datalad_installer Downloading https://api.github.com/repos/datalad/git-annex/actions/artifacts/269005392/zip
Traceback (most recent call last):
  File "/usr/local/bin/datalad-installer", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 2561, in main
    return manager.main(argv)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 692, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 741, in addcomponent
    component(self).provide(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 1158, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 1286, in install
    bindir = self.install_package(package, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 1839, in install_package
    self.download("ubuntu", tmpdir, version)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 1898, in download
    GitHubClient().download_latest_artifact(
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 2253, in download_latest_artifact
    download_zipfile(archive_download_url, target_dir)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 2383, in download_zipfile
    zippath = download_to_tempfile(zip_url, suffix=".zip", headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 2373, in download_to_tempfile
    download_file(url, p, headers)
  File "/usr/local/lib/python3.8/dist-packages/datalad_installer.py", line 2361, in download_file
    with urlopen(req) as r:
  File "/usr/lib/python3.8/urllib/request.py", line [222](https://github.com/datalad/datalad-extensions/runs/6893027819?check_suite_focus=true#step:3:223), in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
Error: Process completed with exit code 1.
```

**Comment by yarikoptic** [comment]
I don't think any change.  I don't see `GITHUB_TOKEN` among secrets here and I would have assumed it did use that autogenerated and it just worked before.  I will provide a custom token secret and see if that one works.

**Comment by yarikoptic** [comment]
well, can't add one due to `Failed to add secret. Secret names must not start with GITHUB_` -- I guess since it is autogenerated. So the question what has changed :-/

**Comment by jwodder** [comment]
@yarikoptic The workflows are [already using](https://github.com/datalad/datalad-extensions/blob/466b06d669d711736d949d22ce443de83bd9e461/.github/workflows/test-datalad_container-maint.yaml#L47) a secret named `datalad_github_token`.

**Comment by yarikoptic** [comment]
d'oh -- right. Reset that one to some new one.  But now wondering if it should be set at all, and shouldn't be just left to be the default one... may be will check later

**Comment by jwodder** [comment]
@yarikoptic Using `secrets.GITHUB_TOKEN` wouldn't work, as that token only grants access to the repository in which it's used (here, datalad/datalad-extensions), whereas we need a token with access to datalad/git-annex.

**Comment by yarikoptic** [comment]
thanks. reupdated with the one which has permissions for access to actions artifacts (tested locally with curl first -seems no error).

**Comment by yarikoptic** [comment]
nope, fails again... 

<details>
<summary>also fails locally for me</summary> 

```shell
$> src/datalad_installer.py --sudo ok git-annex -m datalad/git-annex
2022-06-19T06:35:17-0400 [INFO    ] datalad_installer Writing environment modifications to /home/yoh/.tmp/dl-env-yhlgxk4v.sh
2022-06-19T06:35:17-0400 [INFO    ] datalad_installer Installing git-annex via datalad/git-annex
2022-06-19T06:35:17-0400 [INFO    ] datalad_installer Getting artifacts_url from https://api.github.com/repos/datalad/git-annex/actions/workflows/build-ubuntu.yaml/runs?branch=master
2022-06-19T06:35:18-0400 [INFO    ] datalad_installer Getting archive download URL from https://api.github.com/repos/datalad/git-annex/actions/runs/2522583790/artifacts
2022-06-19T06:35:19-0400 [INFO    ] datalad_installer Downloading artifact package from https://api.github.com/repos/datalad/git-annex/actions/artifacts/273980985/zip
2022-06-19T06:35:19-0400 [INFO    ] datalad_installer Downloading https://api.github.com/repos/datalad/git-annex/actions/artifacts/273980985/zip
Traceback (most recent call last):
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2565, in <module>
    sys.exit(main(sys.argv))
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2561, in main
    return manager.main(argv)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 692, in main
    self.addcomponent(name=cr.name, **cr.kwargs)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 741, in addcomponent
    component(self).provide(**kwargs)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 1158, in provide
    bins = self.get_installer(method).install(self.NAME, **kwargs)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 1286, in install
    bindir = self.install_package(package, **kwargs)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 1839, in install_package
    self.download("ubuntu", tmpdir, version)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 1898, in download
    GitHubClient().download_latest_artifact(
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2253, in download_latest_artifact
    download_zipfile(archive_download_url, target_dir)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2383, in download_zipfile
    zippath = download_to_tempfile(zip_url, suffix=".zip", headers=headers)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2373, in download_to_tempfile
    download_file(url, p, headers)
  File "/home/yoh/proj/datalad/datalad-installer/src/datalad_installer.py", line 2361, in download_file
    with urlopen(req) as r:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

```
</details>

failed with v0.8.0 as well... worked with v0.7.0!  so must be the problem in the code of datalad-installer as I originally suspected -- something got broken! please check/fix

**Comment by jwodder** [comment]
@yarikoptic Fixed by https://github.com/datalad/datalad-installer/pull/111
